// example-timeline/VideoPlayer.tsx
import React, { useRef, useEffect } from "react";

interface VideoPlayerProps {
	videoUrl: string;
	currentTime: number;
	onDurationChange: (duration: number) => void;
	onTimeUpdate: (time: number) => void;
}

const VideoPlayer: React.FC<VideoPlayerProps> = ({
	videoUrl,
	currentTime,
	onDurationChange,
	onTimeUpdate,
}) => {
	const videoRef = useRef<HTMLVideoElement>(null);

	useEffect(() => {
		if (
			videoRef.current &&
			Math.abs(videoRef.current.currentTime - currentTime) > 0.5
		) {
			videoRef.current.currentTime = currentTime;
		}
	}, [currentTime]);

	const handleLoadedMetadata = () => {
		if (videoRef.current) {
			onDurationChange(videoRef.current.duration);
		}
	};

	const handleTimeUpdate = () => {
		if (videoRef.current) {
			onTimeUpdate(videoRef.current.currentTime);
		}
	};

	return (
		<video
			ref={videoRef}
			className="w-full rounded-lg"
			src={videoUrl}
			onLoadedMetadata={handleLoadedMetadata}
			onTimeUpdate={handleTimeUpdate}
			controls
		/>
	);
};

export default VideoPlayer;

// example-timeline/videoplayer.vue
<script setup>
import { ref, watch } from "vue";

const props = defineProps({
	videoUrl: { type: String, required: true },
	currentTime: { type: Number, required: true },
	onDurationChange: { type: Function, required: true },
	onTimeUpdate: { type: Function, required: true },
});

const videoRef = ref(null);

watch(
	() => props.currentTime,
	(newTime) => {
		if (
			videoRef.value &&
			Math.abs(videoRef.value.currentTime - newTime) > 0.5
		) {
			videoRef.value.currentTime = newTime;
		}
	}
);

const handleLoadedMetadata = () => {
	if (videoRef.value) {
		props.onDurationChange(videoRef.value.duration);
	}
};

const handleTimeUpdate = () => {
	if (videoRef.value) {
		props.onTimeUpdate(videoRef.value.currentTime);
	}
};
</script>

<template>
	<video
		ref="videoRef"
		class="w-full rounded-lg"
		:src="props.videoUrl"
		@loadedmetadata="handleLoadedMetadata"
		@timeupdate="handleTimeUpdate"
		controls
	/>
</template>
